Updated to version 4.0.0-pre.2
near-examples/NFT pull request #184
Opened 2021-10-12 09:08 UTC by deveusss

Updated NFT project to version 4.0.0-pre.2, changed account types, gas types, removed absolute code blocks.

2021-11-03 06:01 UTC, thisisjoshford commented
Hey @thedeveus ! Thanks so much for this PR! 🙏🏼  We actually want to wait until the 4.0.0 stable release before we incorporate it with our official examples. When that happens I will certainly reach out to have this PR updated and merged.

2022-02-26 01:09 UTC, BenKurrek requested changes

2022-02-26 01:09 UTC, BenKurrek commented on tests/sim/utils.rs
> +    //let alice = root.create_user(nft.account_id(), to_yocto("100"));
```suggestion
```

2023-10-20 20:06 UTC, gagdiez commented
Outdated

2023-10-20 20:06 UTC, closed without merging